<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <AssemblyName>ArchIQ_Setup_2026</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="ArchIQ_2026.dll" />
    <EmbeddedResource Include="ArchIQ_2026.addin" />
    <EmbeddedResource Include="Newtonsoft.Json.dll" />
  </ItemGroup>
</Project>
